const express=require('express');
const admin=require('firebase-admin');
const jwt=require('jsonwebtoken');
const path=require('path');
const app=express();
app.use(express.json({limit:'2mb'}));

let serviceAccount;
try{ serviceAccount=JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON||'{}'); }catch(e){ console.error('Invalid FIREBASE_SERVICE_ACCOUNT_JSON'); process.exit(1); }
if(!serviceAccount.project_id){ console.error('Missing FIREBASE_SERVICE_ACCOUNT_JSON'); process.exit(1); }
admin.initializeApp({credential:admin.credential.cert(serviceAccount),databaseURL:process.env.FIREBASE_DATABASE_URL});
const db=admin.database();
const messaging=admin.messaging();
const SECRET=process.env.SESSION_SECRET||'change-me';
const ADMIN_UID=process.env.ADMIN_UID||'';
const publicDir=path.join(__dirname,'public');
app.use(express.static(publicDir));

const now=()=>Date.now();
const clean=s=>String(s??'').trim();
const objVals=x=>Object.entries(x||{}).map(([id,v])=>({id,...v}));
function studentToken(student){return jwt.sign({type:'student',studentId:student.id,name:student.name},SECRET,{expiresIn:'12h'});}
function requireStudent(req,res,next){try{const h=req.headers.authorization||'';req.student=jwt.verify(h.replace(/^Bearer\s+/i,''),SECRET);if(req.student.type!=='student')throw Error();next();}catch(e){res.status(401).json({error:'Student login required'});}}
async function requireAdmin(req,res,next){try{const h=req.headers.authorization||'';const token=h.replace(/^Bearer\s+/i,'');const decoded=await admin.auth().verifyIdToken(token);if(decoded.uid!==ADMIN_UID) return res.status(403).json({error:'Not an authorized admin'});req.admin=decoded;next();}catch(e){res.status(401).json({error:'Admin login required'});}}
async function sendToTokens(tokens,title,body,data={}){const t=[...new Set((tokens||[]).filter(Boolean))];if(!t.length)return;try{await messaging.sendEachForMulticast({tokens:t,notification:{title,body},data:Object.fromEntries(Object.entries(data).map(([k,v])=>[k,String(v)])),webpush:{fcmOptions:{link:'/admin.html'}}});}catch(e){console.error('FCM error',e.message);}}
async function adminTokens(){const x=await db.ref('admins/'+ADMIN_UID+'/fcmTokens').once('value');return Object.values(x.val()||{});}

app.get('/api/bootstrap',async(req,res)=>{const s=(await db.ref('settings').once('value')).val()||{};res.json({siteName:s.siteName||'SEVEN NURSES',headerTitle:s.headerTitle||'SEVEN NURSES',subtitle:s.subtitle||'Online Nursing Examination',logoUrl:s.logoUrl||'',backgroundUrl:s.backgroundUrl||'',notice:s.notice||'',footerText:s.footerText||'© SEVEN NURSES',passMarkDefault:s.passMarkDefault??40});});

app.post('/api/student/login',async(req,res)=>{const name=clean(req.body.name),pin=clean(req.body.pin);if(!name||!pin)return res.status(400).json({error:'Name and PIN are required'});const s=(await db.ref('settings/commonExamPin').once('value')).val();if(String(s||'')!==pin)return res.status(401).json({error:'Wrong Exam PIN'});const snap=await db.ref('students').orderByChild('nameLower').equalTo(name.toLowerCase()).once('value');let student=null;snap.forEach((v)=>{if(v.val()?.active!==false)student={id:v.key,name:v.val().name};});if(!student)return res.status(401).json({error:'Student name is not registered or inactive'});res.json({token:studentToken(student),student});});
app.get('/api/student/exams',requireStudent,async(req,res)=>{const x=objVals((await db.ref('exams').once('value')).val()).filter(e=>e.active!==false).sort((a,b)=>(a.order||0)-(b.order||0));res.json(x.map(e=>({id:e.id,title:e.title,duration:e.duration||30,passMark:e.passMark??40,totalQuestions:e.totalQuestions||0,order:e.order||0})));});
app.get('/api/student/exam/:id',requireStudent,async(req,res)=>{const e=(await db.ref('exams/'+req.params.id).once('value')).val();if(!e||e.active===false)return res.status(404).json({error:'Exam not found'});const q=objVals((await db.ref('questions').orderByChild('examId').equalTo(req.params.id).once('value')).val()).sort((a,b)=>(a.order||0)-(b.order||0));res.json({exam:{id:req.params.id,title:e.title,duration:e.duration||30,passMark:e.passMark??40,totalQuestions:q.length},questions:q.map(x=>({id:x.id,question:x.question,imageUrl:x.imageUrl||'',order:x.order||0,options:Object.fromEntries(['A','B','C','D','E'].map(k=>[k,{text:x.options?.[k]?.text||''}]))}))});});
app.post('/api/student/submit',requireStudent,async(req,res)=>{const {examId,answers}=req.body;const exam=(await db.ref('exams/'+examId).once('value')).val();if(!exam)return res.status(404).json({error:'Exam not found'});const qs=objVals((await db.ref('questions').orderByChild('examId').equalTo(examId).once('value')).val()).sort((a,b)=>(a.order||0)-(b.order||0));let score=0;const review=qs.map((q,i)=>{const given=answers?.[q.id]||{};const correct={};let ok=true;for(const k of ['A','B','C','D','E']){correct[k]=!!q.options?.[k]?.correct;if(Boolean(given[k])!==correct[k])ok=false;}if(ok)score++;return {number:i+1,question:q.question,options:Object.fromEntries(['A','B','C','D','E'].map(k=>[k,{text:q.options?.[k]?.text||'',selected:Boolean(given[k]),correct:correct[k]}])),isCorrect:ok};});const total=qs.length,percentage=total?Math.round(score/total*10000)/100:0;const grade=percentage>=80?'A+':percentage>=70?'A':percentage>=60?'A-':percentage>=50?'B':percentage>=40?'C':'F';const status=percentage>=(exam.passMark??40)?'PASS':'FAIL';const submissionId=db.ref('submissions').push().key;const resultId=db.ref('results').push().key;const base={studentId:req.student.studentId,studentName:req.student.name,examId,examTitle:exam.title,score,total,percentage,grade,passMark:exam.passMark??40,status,submittedAt:now(),review};await db.ref('submissions/'+submissionId).set({...base,answers});await db.ref('results/'+resultId).set(base);const all=objVals((await db.ref('results').orderByChild('examId').equalTo(examId).once('value')).val()).sort((a,b)=>b.score-a.score||a.submittedAt-b.submittedAt);const rank=all.findIndex(r=>r.id===resultId)+1;await db.ref('results/'+resultId+'/rank').set(rank);const totalExaminees=all.length;const at=await adminTokens();await sendToTokens(at,'New Exam Submission',`${req.student.name} submitted ${exam.title}: ${score}/${total} (${grade})`,{type:'result',resultId,examId});res.json({resultId,score,total,percentage,grade,status,passMark:exam.passMark??40,rank,totalExaminees,review});});
app.get('/api/student/result/:id',requireStudent,async(req,res)=>{const r=(await db.ref('results/'+req.params.id).once('value')).val();if(!r||r.studentId!==req.student.studentId)return res.status(404).json({error:'Result not found'});const all=objVals((await db.ref('results').orderByChild('examId').equalTo(r.examId).once('value')).val()).sort((a,b)=>b.score-a.score||a.submittedAt-b.submittedAt);const rank=all.findIndex(x=>x.id===req.params.id)+1;res.json({...r,rank,totalExaminees:all.length});});
app.get('/api/student/notifications',requireStudent,async(req,res)=>{const x=(await db.ref('notifications/students/'+req.student.studentId).once('value')).val()||{};res.json(objVals(x).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)));});
app.post('/api/student/fcm-token',requireStudent,async(req,res)=>{const token=clean(req.body.token);if(token)await db.ref(`students/${req.student.studentId}/fcmTokens`).push(token);res.json({ok:true});});

app.get('/api/admin/stats',requireAdmin,async(req,res)=>{const [s,e,r]=await Promise.all([db.ref('students').once('value'),db.ref('exams').once('value'),db.ref('results').once('value')]);res.json({students:s.numChildren(),exams:e.numChildren(),results:r.numChildren()});});
app.get('/api/admin/settings',requireAdmin,async(req,res)=>{res.json((await db.ref('settings').once('value')).val()||{});});
app.put('/api/admin/settings',requireAdmin,async(req,res)=>{const b=req.body||{};const allowed=['siteName','headerTitle','subtitle','logoUrl','backgroundUrl','notice','footerText','commonExamPin','passMarkDefault'];const out={};for(const k of allowed)if(b[k]!==undefined)out[k]=b[k];await db.ref('settings').update(out);res.json({ok:true});});
app.get('/api/admin/students',requireAdmin,async(req,res)=>{res.json(objVals((await db.ref('students').once('value')).val()).sort((a,b)=>a.name.localeCompare(b.name)));});
app.post('/api/admin/students',requireAdmin,async(req,res)=>{const name=clean(req.body.name);if(!name)return res.status(400).json({error:'Name required'});const id=req.body.id||db.ref('students').push().key;await db.ref('students/'+id).update({name, nameLower:name.toLowerCase(),active:req.body.active!==false});res.json({id});});
app.delete('/api/admin/students/:id',requireAdmin,async(req,res)=>{await db.ref('students/'+req.params.id).remove();res.json({ok:true});});
app.get('/api/admin/exams',requireAdmin,async(req,res)=>{res.json(objVals((await db.ref('exams').once('value')).val()).sort((a,b)=>(a.order||0)-(b.order||0)));});
app.post('/api/admin/exams',requireAdmin,async(req,res)=>{const b=req.body,id=b.id||db.ref('exams').push().key;await db.ref('exams/'+id).set({title:clean(b.title),duration:Number(b.duration)||30,passMark:Number(b.passMark??40),active:b.active!==false,order:Number(b.order)||0,totalQuestions:Number(b.totalQuestions)||0});res.json({id});});
app.delete('/api/admin/exams/:id',requireAdmin,async(req,res)=>{await db.ref('exams/'+req.params.id).remove();const q=(await db.ref('questions').orderByChild('examId').equalTo(req.params.id).once('value')).val()||{};await Promise.all(Object.keys(q).map(id=>db.ref('questions/'+id).remove()));res.json({ok:true});});
app.get('/api/admin/questions/:examId',requireAdmin,async(req,res)=>{res.json(objVals((await db.ref('questions').orderByChild('examId').equalTo(req.params.examId).once('value')).val()).sort((a,b)=>(a.order||0)-(b.order||0)));});
app.post('/api/admin/questions',requireAdmin,async(req,res)=>{const b=req.body,id=b.id||db.ref('questions').push().key;const options={};for(const k of ['A','B','C','D','E'])options[k]={text:clean(b.options?.[k]?.text),correct:Boolean(b.options?.[k]?.correct)};await db.ref('questions/'+id).set({examId:b.examId,question:clean(b.question),imageUrl:clean(b.imageUrl),order:Number(b.order)||0,mark:1,options});res.json({id});});
app.delete('/api/admin/questions/:id',requireAdmin,async(req,res)=>{await db.ref('questions/'+req.params.id).remove();res.json({ok:true});});
app.get('/api/admin/results',requireAdmin,async(req,res)=>{const x=objVals((await db.ref('results').once('value')).val()).sort((a,b)=>(b.submittedAt||0)-(a.submittedAt||0));res.json(x.map(r=>({...r,review:undefined})));});
app.get('/api/admin/results/:id',requireAdmin,async(req,res)=>{const r=(await db.ref('results/'+req.params.id).once('value')).val();if(!r)return res.status(404).json({error:'Not found'});res.json(r);});
app.get('/api/admin/notifications',requireAdmin,async(req,res)=>{const x=(await db.ref('notifications/admins').once('value')).val()||{};res.json(objVals(x).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)));});
app.post('/api/admin/fcm-token',requireAdmin,async(req,res)=>{const token=clean(req.body.token);if(token)await db.ref(`admins/${ADMIN_UID}/fcmTokens`).push(token);res.json({ok:true});});

app.use((req,res,next)=>{if(req.method==='GET'&&!req.path.startsWith('/api/'))return res.sendFile(path.join(publicDir,'index.html'));next();});
const port=process.env.PORT||10000;app.listen(port,()=>console.log('SEVEN NURSES running on '+port));
